---
- name: Daily Backup
  hosts: all
  gather_facts: false
  vars:
        date: "{{ lookup('pipe', 'date +%b%d') }}"
        src_path: \\192.168.56.16\Scratch\Scratch\New folder\MSI\
        dest_path: D:\Test
  tasks:
    - name: Creating a new folder with the current date
      ansible.windows.win_file:
      # Create a new folder with the current date
          path: "{{ dest_path }}"\"{{ date }}"
          state: directory
      tags:
      - Create_Folder

    - name: Copying the specified contents using Fastcopy cmd (win_command)
      ansible.windows.win_command:
        cmd: C:\Users\itsupport\FastCopy\fcp.exe /cmd=diff /speed=full /no_confirm_stop /force_start /log "{{ src_path }}" /to="{{ dest_path }}\{{ date }}"
      become: true
      become_method: runas
      become_flags: logon_type=new_credentials logon_flags=netcredentials_only
      tags:
      - Copy