---
- name: Daily Backup
  hosts: all
  gather_facts: false
  vars:
        date: "{{ lookup('pipe', 'date +%m%d') }}"
  tasks:
    - name: Creating a new folder with the current date
      ansible.windows.win_file:
      # Create a new folder with the current date
          path: D:\Test\{{ date }}
          state: directory
      tags:
      - Create_Folder