---
- name: Execute custom CMD command on Windows hosts
  hosts: win
  gather_facts: false
  tasks:
    - name: Execute shutdown force command
      ansible.windows.win_command:
        cmd: shutdown /s /f
