---
- name: Install MSI using win_package module (UNC)
  hosts: all
  gather_facts: false
  tasks:
    - name: Silent install PDF Sam MSI using win_package from the specified UNC path
      ansible.windows.win_package:
      # Specify the install_path on Variables in AWX before running
        path: '{{ install_path }}\pdfsam-5.1.1.msi'
        state: present
        arguments: /qb /norestart CHECK_FOR_UPDATES=false DONATE_NOTIFICATION=false SKIPTHANKSPAGE=Yes