---
- name: Install MSI using win_package module
  hosts: win
  gather_facts: false
  tasks:
    - name: Silent install PDF Sam MSI using win_package
      ansible.windows.win_package:
        path: https://github.com/torakiki/pdfsam/releases/download/v5.1.2/pdfsam-5.1.2.msi
        state: present
        arguments: /qb /norestart CHECK_FOR_UPDATES=false DONATE_NOTIFICATION=false SKIPTHANKSPAGE=Yes