---
- name: Daily Backup
  hosts: all
  gather_facts: false
  vars:
        date: "{{ lookup('pipe', 'date +%b%d') }}"
  tasks:
    - name: Creating a new folder with the current date
      ansible.windows.win_file:
      # Create a new folder with the current date
          path: D:\Test\{{ date }}
          state: directory
      tags:
      - Create_Folder

    - name: Copying the specified contents using Fastcopy cmd (win_command)
      ansible.windows.win_command:
      # Specify the install_path on Variables in AWX before running
        cmd: C:\Users\itsupport\FastCopy\fcp.exe /cmd=diff /speed=full /no_confirm_stop /force_start `"{{C:\MSI\}}`" /to=`"{{D:\Test\{{ date }}\}}`"
      # become: true
      # become_method: runas
      # become_flags: logon_type=new_credentials logon_flags=netcredentials_only
      tags:
      - Copy