---
- name: win_wsus_fix
  hosts: all
  gather_facts: false
  tasks:
    - name: Stop Windows Update service
      ansible.windows.win_service:
        name: wuauserv
        state: stopped
      async: 45
      poll: 5
    
    # Delete the Test value
    - name: Delete Test value
      ansible.windows.win_regedit:
        path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\WindowsUpdate
        name: Test
        type: string
        state: absent
    
    - name: Start Windows Update service
      ansible.windows.win_service:
        name: wuauserv
        state: started
      async: 45
      poll: 5
        


