---
- name: Registry fix for WSUS Clients
  hosts: all
  gather_facts: false
  tasks:
    - name: Stopping Windows Update service
      ansible.windows.win_service:
        name: wuauserv
        state: stopped
      async: 45
      poll: 5
    
    - name: Deleting the PingID value from path
      ansible.windows.win_regedit:
        path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\WindowsUpdate
        name: PingID
        state: absent
    
    - name: Deleting the AccountDomainSid value from path
      ansible.windows.win_regedit:
        path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\WindowsUpdate
        name: AccountDomainSid
        state: absent
    
    - name: Deleting the SusClientId value from path
      ansible.windows.win_regedit:
        path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\WindowsUpdate
        name: SusClientId
        type: string
        state: absent
    
    - name: Deleting the SusClientIDValidation value from path
      ansible.windows.win_regedit:
        path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\WindowsUpdate
        name: SusClientIDValidation
        type: binary
        state: absent

    - name: Starting Windows Update service
      ansible.windows.win_service:
        name: wuauserv
        state: started
      async: 45
      poll: 5
    
    - name: Reset Auth and Detect
      ansible.windows.win_command:
        cmd: 'wuauclt "/resetauthorization" "/detectnow"'

    - name: Detecting and Reporting back to WSUS
      ansible.windows.win_command:
        cmd: 'wuauclt "/detectnow" "/reportnow"'

    - name: Detecting and Reporting back to WSUS
      ansible.windows.win_command:
        cmd: 'wuauclt "/detectnow" "/reportnow"'
    
    - name: Detecting and Reporting back to WSUS
      ansible.windows.win_command:
        cmd: 'wuauclt "/detectnow" "/reportnow"'


