---
- name: Install MSI using win_package module (UNC)
  hosts: all
  gather_facts: false
  become: true
  become_method: runas
  become_flags: logon_type=new_credentials logon_flags=netcredentials_only
  vars:
    ansible_become_user: '{{ pass1_user }}'
    ansible_become_password: '{{ pass1_pwd }}'
  
  tasks:
    - name: Silent install PDF Sam MSI using win_package from the specified UNC path
      ansible.windows.win_package:
      # Specify the install_path on Variables in AWX before running
        path: '{{ install_path }}\pdfsam-5.1.1.msi'
        state: present
        arguments: /qb /norestart CHECK_FOR_UPDATES=false DONATE_NOTIFICATION=false SKIPTHANKSPAGE=Yes
      tags:
      - PDF_Sam
      ignore_errors: true

    - name: Silent install Google Chrome MSI using win_package from the specified UNC path
      ansible.windows.win_package:
      # Specify the install_path on Variables in AWX before running
        path: '{{ install_path }}\googlechromestandaloneenterprise64.msi'
        state: present
        arguments: /q /norestart
      tags:
      - Google_Chrome
      ignore_errors: true

    - name: Silent install Foxit Reader MSI using win_package from the specified UNC path
      ansible.windows.win_package:
      # Specify the install_path on Variables in AWX before running
        path: '{{ install_path }}\FoxitPDFReader121_enu_Setup.msi'
        state: present
        arguments: /q /norestart
      tags:
      - Foxit
      ignore_errors: true

    - name: Silent install Autodesk Design Review using win_package from the specified UNC path
      ansible.windows.win_package:
      # Specify the install_path on Variables in AWX before running
        path: '{{ install_path }}\AutodeskDesignReview\x86\ADR\SetupDesignReview.msi'
        state: present
        arguments: /quiet /norestart
      tags:
      - Design_Review
      ignore_errors: true

    - name: Silent install LibreOffice using win_package from the specified UNC path
      ansible.windows.win_package:
      # Specify the install_path on Variables in AWX before running
        path: '{{ install_path }}\LibreOffice_7.5.5.msi'
        state: present
        arguments: /q /norestart
      tags:
      - LibreOffice
      ignore_errors: true

    - name: Silent install Bitdefender using cmd (win_command)
      ansible.windows.win_shell:
      # Specify the install_path on Variables in AWX before running
        cmd: '{{ install_path }}\Bitdefender\epskit_x64.exe /bdparams /silent'
      tags:
      - Bitdefender
      ignore_errors: true