---
- name: Find PC Model, Serial number and OS Key
  hosts: all
  gather_facts: false
  tasks:
  - name: Silent install Outlook for Windows using win_powershell from the specified UNC path
      ansible.windows.win_powershell:
      # Specify the install_path on Variables in AWX before running
        script: |
        # Get and store the values
        $computerSystem = Get-WmiObject -Class Win32_ComputerSystem
        $model = $computerSystem.Model
        $manufacturer = $computerSystem.Manufacturer
        $key = (Get-WmiObject -query "select * from SoftwareLicensingService").OA3xOriginalProductKey

        #Display the values
        Write-Output "Computer Name: $env:COMPUTERNAME"
        Write-Output "Computer Model: $model"
        Write-Output "Manufacturer: $manufacturer"
        Write-Output "Windows Key: $key"
