---
- name: win_uptime
  hosts: all
  gather_facts: false
  tasks:
    - name: Finding uptime/boottime
      ansible.windows.win_powershell:
        script: |
          Get-CimInstance -ClassName win32_operatingsystem | select csname, lastbootuptime
      ignore_errors: true
