---
- name: Install MSI using win_package module (UNC)
  hosts: all
  gather_facts: false
  become: true
  become_method: runas
  become_flags: logon_type=new_credentials logon_flags=netcredentials_only
  vars:
    ansible_become_user: '{{ pass1_user }}'
    ansible_become_password: '{{ pass1_pwd }}'
  
  tasks:
    - name: Silent install PDF Sam MSI using win_package from the specified UNC path
      ansible.windows.win_package:
      # Specify the install_path on Variables in AWX before running
        path: '{{ install_path }}\pdfsam-5.1.1.msi'
        state: present
        arguments: /qb /norestart CHECK_FOR_UPDATES=false DONATE_NOTIFICATION=false SKIPTHANKSPAGE=Yes
      tags:
      - PDF_Sam
      ignore_errors: true

    - name: Silent install Google Chrome MSI using win_package from the specified UNC path
      ansible.windows.win_package:
      # Specify the install_path on Variables in AWX before running
        path: '{{ install_path }}\googlechromestandaloneenterprise64.msi'
        state: present
        arguments: /q /norestart
      tags:
      - Google_Chrome
      ignore_errors: true

    - name: Silent install Foxit Reader MSI using win_package from the specified UNC path
      ansible.windows.win_package:
      # Specify the install_path on Variables in AWX before running
        path: '{{ install_path }}\FoxitPDFReader121_enu_Setup.msi'
        state: present
        arguments: /q /norestart
      tags:
      - Foxit
      ignore_errors: true

    - name: Silent install Autodesk Design Review using win_package from the specified UNC path
      ansible.windows.win_package:
      # Specify the install_path on Variables in AWX before running
        path: '{{ install_path }}\AutodeskDesignReview\x86\ADR\SetupDesignReview.msi'
        state: present
        arguments: /quiet /norestart
      tags:
      - Design_Review
      ignore_errors: true

    - name: Silent install Autodesk Diroots ProSheets Addin using win_package from the specified UNC path
      ansible.windows.win_package:
      # Specify the install_path on Variables in AWX before running
        path: '{{ install_path }}\Autodesk\Addons\Diroots_Prosheet\ProSheets_12130.exe'
        state: present
        arguments: /i // /qn accept_eula=1
      tags:
      - Prosheets
      ignore_errors: true

    - name: Silent install LibreOffice using win_package from the specified UNC path
      ansible.windows.win_package:
      # Specify the install_path on Variables in AWX before running
        path: '{{ install_path }}\LibreOffice_7.5.5.msi'
        state: present
        arguments: /q /norestart
      tags:
      - LibreOffice
      ignore_errors: true

    - name: Silent install Outlook for Windows using win_powershell from the specified UNC path
      ansible.windows.win_powershell:
      # Specify the install_path on Variables in AWX before running
        script: |
          $apiUrl = "https://store.rg-adguard.net/api/GetFiles"

          $productUrl = "https://www.microsoft.com/store/productId/{{ app_id }}" # Specify the app id
          #$productUrl = "https://www.microsoft.com/store/productId/9NRX63209R7B" # Outlook for Windows
          #$productUrl = "https://www.microsoft.com/store/productId/9NBLGGH4NNS1" # App Installer

          $downloadFolder = Join-Path $env:TEMP "StoreDownloads"
          if(!(Test-Path $downloadFolder -PathType Container)) {
              New-Item $downloadFolder -ItemType Directory -Force
          }

          $body = @{
              type = 'url'
              url  = $productUrl
              ring = 'RP'
              lang = 'en-US'
          }

          $raw = Invoke-RestMethod -Method Post -Uri $apiUrl -ContentType 'application/x-www-form-urlencoded' -Body $body

          $raw | Select-String '<tr style.*<a href=\"(?<url>.*)"\s.*>(?<text>.*)<\/a>' -AllMatches|
          % { $_.Matches } |
          % { 
              $url = $_.Groups[1].Value
              $text = $_.Groups[2].Value
              Write-Host $text

              if($text -match "_(x64).*msix(|bundle)$") {
                  $downloadFile = Join-Path $downloadFolder $text
                  if(!(Test-Path $downloadFile)) {
                      Invoke-WebRequest -Uri $url -OutFile $downloadFile
                  }
              }
          }

          cd $downloadFolder
          $packPath = Get-Item Microsoft.OutlookForWindows*.msix

          DISM.EXE /Online /Add-ProvisionedAppxPackage /PackagePath:$packPath /SkipLicense

      tags:
        - OFW_Machine
      ignore_errors: true

    - name: Silent install Outlook for Windows using win_powershell from the specified UNC path
      ansible.windows.win_powershell:
      # Specify the install_path on Variables in AWX before running
        script: |
          $packPath = {{ install_path }}\Outlook_for_Windows.appx
          DISM.EXE /Online /Add-ProvisionedAppxPackage /PackagePath:$packPath /SkipLicense
        
      tags:
        - OFW_Machine2
      ignore_errors: true

    - name: Silent install Outlook for Windows using win_package
      ansible.windows.win_package:
      # Specify the install_path on Variables in AWX before running
        path: '{{ install_path }}\Outlook_for_Windows.appx'
        state: present
      tags:
        - OFW_User
      ignore_errors: true
  
    - name: Silent install Bitdefender using cmd (win_command)
      ansible.windows.win_command:
      # Specify the install_path on Variables in AWX before running
        cmd: '{{ install_path }}\Bitdefender\epskit_x64.exe /bdparams /silent'
      tags:
        - Bitdefender
      # ignore_errors: true
      register: bitdefender
      failed_when: bitdefender.rc != 1 and bitdefeder.rc != 0