---
- name: Display a message and a notification before shutdown
  hosts: all
  gather_facts: false
  tasks:
    - name: Displaying a Shutdown message
      community.windows.win_msg:
        display_seconds: 240
        msg: "Maintenance Alert: The PC is going to shutdown now. Please Save and close applications and sign out. Thank you!"
      ignore_errors: true

    - name: Display a Shutdown ttoast message
      community.windows.win_toast:
        expire: 240
        title: Maintenance Alert: The PC is going to shutdown now. Please Save and close applications and sign out. Thank you!
        msg: Maintenace Alert
      async: 60
      poll: 0
      ignore_errors: true