---
- name: Daily Backup
  hosts: all
  gather_facts: false
  vars:
        date: "{{ lookup('pipe', 'date +%b%d') }}"
        src_path1: \\192.168.56.16\Scratch\Scratch\New folder\MSI\
        dest_path1: D:\Test\
        src_path2: \\192.168.56.16\Scratch\Scratch\New folder2\MSI\
        dest_path2: D:\Test2\
  tasks:
    - name: Creating a new folder with the current date
      ansible.windows.win_file:
      # Create a new folder with the current date
          path: "{{ dest_path1 }}{{ date }}"
          state: directory
      tags:
      - Create_Folder1

    - name: Creating a new folder with the current date
      ansible.windows.win_file:
      # Create a new folder with the current date
          path: "{{ dest_path2 }}{{ date }}"
          state: directory
      tags:
      - Create_Folder2

    - name: One - Copying the specified contents using Fastcopy cmd (win_command)
      ansible.windows.win_command:
        cmd: C:\Users\itsupport\FastCopy\fcp.exe /cmd=diff /speed=full /no_confirm_stop /force_start /log "{{ src_path1 }}" /to="{{ dest_path1 }}{{ date }}"
      become: true
      become_method: runas
      become_flags: logon_type=new_credentials logon_flags=netcredentials_only
      tags:
      - Copy1

    - name: Two - Copying the specified contents using Fastcopy cmd (win_command)
      ansible.windows.win_command:
        cmd: C:\Users\itsupport\FastCopy\fcp.exe /cmd=diff /speed=full /no_confirm_stop /force_start /log "{{ src_path2 }}" /to="{{ dest_path2 }}{{ date }}"
      become: true
      become_method: runas
      become_flags: logon_type=new_credentials logon_flags=netcredentials_only
      tags:
      - Copy2