---
- name: win_reboot_msg
  hosts: all
  gather_facts: false
  tasks:
    - name: With start and end sound
      community.windows.win_say:
        start_sound_path: C:\Windows\Media\Windows Exclamation.wav
        msg: Weekly System Restart Reminder
        end_sound_path: C:\Windows\Media\Windows Message Nudge.wav
        voice: Microsoft Hazel Desktop

    - name: Display a message (Reboot message)
      community.windows.win_msg:
        display_seconds: 240
        msg: Weekly System Restart Reminder - In accordance with our work-from-home guidelines, a weekly system restart is a mandatory procedure to ensure optimal performance and functionality of your device. The PC will automatically restart in 30 minutes. Please close all the applications and sign out.
      
    - name: Display a toast message (Reboot message)
      community.windows.win_toast:
        expire: 240
        title: In accordance with our work-from-home guidelines, a weekly system restart is a mandatory procedure to ensure optimal performance and functionality of your device.\n The PC will automatically restart in 30 minutes. Please close all the applications and sign out.
        msg: Weekly System Restart Reminder
      async: 60
      poll: 0