---
- name: Install applications from the Web
  hosts: all
  gather_facts: false
  tasks:
    - name: Silent install PDF Sam MSI using win_package
      ansible.windows.win_package:
        path: https://github.com/torakiki/pdfsam/releases/download/v5.1.2/pdfsam-5.1.2.msi
        state: present
        arguments: /qb /norestart CHECK_FOR_UPDATES=false DONATE_NOTIFICATION=false SKIPTHANKSPAGE=Yes
      tags:
        - PDF_Sam
      ignore_errors: true

    - name: Install Store App Outlook for Windows (New) using Winget
      ansible.windows.win_command:
        cmd: winget install 9NRX63209R7B --source winget --accept-source-agreements --accept-package-agreements
      tags:
        - Outlook_Winget
      ignore_errors: true
  